[phases.setup]
nixPkgs = ["nodejs_18", "python39", "pip"]

[phases.install]
cmds = ["npm ci", "pip install -r requirements.txt"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "python app.py"